services:
  - type: web
    name: achai-api
    runtime: docker
    plan: free
    region: virginia
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    autoDeployTrigger: checksPass
    envVars:
      - key: ForwardedHeaders__ClientIpHeader
        value: True-Client-IP
    buildFilter:
      paths:
        - src/api/**
        - Dockerfile
        - .dockerignore
        - render.yaml
